# ethtool

ETHTOOL_VERSION_BASE = 5.8
ETHTOOL_HASH = 88ca347ef35acb16ec0a0107f55ab599ddb18f56
export ETHTOOL_VERSION_BASE
export ETHTOOL_HASH

ETHTOOL = ethtool
$(ETHTOOL)_SRC_PATH = $(SRC_PATH)/$(ETHTOOL)
$(ETHTOOL)_PATH = $(BUSTER_FILES_PATH)/$(ETHTOOL)
SONIC_MAKE_FILES += $(ETHTOOL)
SONIC_COPY_FILES += $(ETHTOOL)

export ETHTOOL
