# ethtool

ETHTOOL_VERSION_BASE = 5.8
export ETHTOOL_VERSION_BASE

ETHTOOL = ethtool
$(ETHTOOL)_SRC_PATH = $(SRC_PATH)/$(ETHTOOL)
$(ETHTOOL)_PATH = $(BUSTER_FILES_PATH)/$(ETHTOOL)
SONIC_MAKE_FILES += $(ETHTOOL)
SONIC_COPY_FILES += $(ETHTOOL)

export ETHTOOL
